all:
  vars:
      ansible_user: manager
      ansible_become: true
      ansible_become_method: su
      ansible_become_user: root
      ansible_python_interpreter: /bin/ash
  hosts:
    spine1:
        ansible_host: 192.168.0.1
        interfaces:
            lo: 1.0.0.1/32
            eth1: 10.0.0.1/30
            eth2: 10.0.0.5/30
            eth3: 10.0.0.9/30
            eth4: 10.0.0.13/30
            eth5: 10.0.0.17/30
            eth6: 10.0.0.21/30
            eth7: 10.0.0.25/30
            eth8: 10.0.0.29/30
        neighbors:
            - 2.0.0.1
            - 2.0.0.2
            - 2.0.0.3
            - 2.0.0.4
    spine2:
        ansible_host: 192.168.0.2
        interfaces:
            lo: 1.0.0.2/32
            eth1: 10.0.0.33/30
            eth2: 10.0.0.37/30
            eth3: 10.0.0.41/30
            eth4: 10.0.0.45/30
            eth5: 10.0.0.49/30
            eth6: 10.0.0.53/30
            eth7: 10.0.0.57/30
            eth8: 10.0.0.61/30
        neighbors:
            - 2.0.0.1
            - 2.0.0.2
            - 2.0.0.3
            - 2.0.0.4
    leaf1:
        ansible_host: 192.168.0.3
        interfaces:
            lo: 2.0.0.1/32
            eth1: 10.0.0.2/30
            eth2: 10.0.0.6/30
            eth3: 10.0.0.34/30
            eth4: 10.0.0.38/30
        spines:
            - 1.0.0.1
            - 1.0.0.2
        servers:
            - 10.1.0.2
            - 10.1.0.3
            - 10.1.0.4
        server_net_ip: 10.1.0.1

    leaf2:
        ansible_host: 192.168.0.4
        interfaces:
            lo: 2.0.0.2/32
            eth1: 10.0.0.10/30
            eth2: 10.0.0.14/30
            eth3: 10.0.0.42/30
            eth4: 10.0.0.46/30
        spines:
            - 1.0.0.1
            - 1.0.0.2
        servers:
            - 10.2.0.2
            - 10.2.0.3
            - 10.2.0.4
        server_net_ip: 10.2.0.1
    leaf3:
        ansible_host: 192.168.0.5
        interfaces:
            lo: 2.0.0.3/32
            eth1: 10.0.0.18/30
            eth2: 10.0.0.22/30
            eth3: 10.0.0.50/30
            eth4: 10.0.0.54/30
        spines:
           - 1.0.0.1
           - 1.0.0.2
        servers:
           - 10.3.0.2
           - 10.3.0.3
           - 10.3.0.4
        server_net_ip: 10.3.0.1
           
    leaf4:
        ansible_host: 192.168.0.6
        interfaces:
            lo: 2.0.0.4/32
            eth1: 10.0.0.26/30
            eth2: 10.0.0.30/30
            eth3: 10.0.0.58/30
            eth4: 10.0.0.62/30
        spines:
            - 1.0.0.1
            - 1.0.0.2
        server_net_ip: 10.4.0.1
        servers:
            - 10.4.0.2
            - 10.4.0.3
            - 10.4.0.4

    server1:
        ansible_host: 192.168.0.7
        server_net_ip: 10.1.0.2
        gateway: 10.1.0.1
        leafs:
            - 10.1.0.1
        ips_vm:
            - 8.8.8.1/24
    server2:
        ansible_host: 192.168.0.8
        server_net_ip: 10.1.0.3
        gateway: 10.1.0.1
        leafs:
            - 10.1.0.1
        ips_vm:
            - 8.8.8.2/24
    server3:
        ansible_host: 192.168.0.9
        server_net_ip: 10.1.0.4
        gateway: 10.1.0.1
        leafs:
            - 10.1.0.1

    server4:
        ansible_host: 192.168.0.10
        server_net_ip: 10.2.0.2
        gateway: 10.2.0.1
        leafs:
           - 10.2.0.1

    server5:
        ansible_host: 192.168.0.11
        server_net_ip: 10.2.0.3
        gateway: 10.2.0.1
        leafs:
            - 10.2.0.1
        ips_vm:
            - 8.8.8.1/24
    server6:
        ansible_host: 192.168.0.12
        server_net_ip: 10.2.0.4
        gateway: 10.2.0.1
        leafs:
            - 10.2.0.1
        ips_vm:
            - 8.8.8.2/24

    server7:
        ansible_host: 192.168.0.13
        server_net_ip: 10.3.0.2
        gateway: 10.3.0.1
        leafs:
            - 10.3.0.1
    server8:
        ansible_host: 192.168.0.14
        server_net_ip: 10.3.0.3
        gateway: 10.3.0.1
        leafs:
           - 10.3.0.1
    server9:
        ansible_host: 192.168.0.15
        server_net_ip: 10.3.0.4
        gateway: 10.3.0.1
        leafs:
            - 10.3.0.1
        ips_vm:
            - 8.8.8.1/24

    server10:
        ansible_host: 192.168.0.16
        server_net_ip: 10.4.0.2
        gateway: 10.4.0.1
        leafs:
            - 10.4.0.1
        ips_vm:
            - 8.8.8.2/24
    server11:
        ansible_host: 192.168.0.17
        server_net_ip: 10.4.0.3
        gateway: 10.4.0.1
        leafs:
            - 10.4.0.1
    server12:
        ansible_host: 192.168.0.18
        server_net_ip: 10.4.0.4
        gateway: 10.4.0.1
        leafs:
           - 10.4.0.1

spines:
    hosts:
        spine1:
        spine2:
leafs:
    hosts:
        leaf1:
        leaf2:
        leaf3:
        leaf4:

servers:
    hosts:
        server1:
        server2:
        server3:
        server4:
        server5:
        server6:
        server7:
        server8:
        server9:
        server10:
        server11:
        server12:    
