all:
  vars:
    ansible_user: root
    ansible_connection: local
    
  hosts:
    # Spines
    spine1:
        ansible_docker_container: clab-tfg-frr-ansible-spine1
        interfaces:
            lo: 1.0.0.1/32
            eth1: 10.0.0.1/30
            eth2: 10.0.0.5/30
            eth3: 10.0.0.9/30
            eth4: 10.0.0.13/30
            eth5: 10.0.0.17/30
            eth6: 10.0.0.21/30
            eth7: 10.0.0.25/30
            eth8: 10.0.0.29/30
        neighbors:
            - 2.0.0.1
            - 2.0.0.2
            - 2.0.0.3
            - 2.0.0.4
    spine2:
        ansible_docker_container: clab-tfg-frr-ansible-spine2
        interfaces:
            lo: 1.0.0.2/32
            eth1: 10.0.0.33/30
            eth2: 10.0.0.37/30
            eth3: 10.0.0.41/30
            eth4: 10.0.0.45/30
            eth5: 10.0.0.49/30
            eth6: 10.0.0.53/30
            eth7: 10.0.0.57/30
            eth8: 10.0.0.61/30
        neighbors:
            - 2.0.0.1
            - 2.0.0.2
            - 2.0.0.3
            - 2.0.0.4
    
    # Leafs
    leaf1:
        ansible_docker_container: clab-tfg-frr-ansible-leaf1
        interfaces:
            lo: 2.0.0.1/32
            eth1: 10.0.0.2/30
            eth2: 10.0.0.6/30
            eth3: 10.0.0.34/30
            eth4: 10.0.0.38/30
        spines:
            - 1.0.0.1
            - 1.0.0.2
        servers:
            - 10.1.0.2
            - 10.1.0.3
            - 10.1.0.4
            - 10.1.0.5
            - 10.1.0.6
            - 10.1.0.7
            - 10.1.0.8
            - 10.1.0.9
            - 10.1.0.10
            - 10.1.0.11
            - 10.1.0.12
            - 10.1.0.13
        server_net_ip: 10.1.0.1

    leaf2:
        ansible_docker_container: clab-tfg-frr-ansible-leaf2
        interfaces:
            lo: 2.0.0.2/32
            eth1: 10.0.0.10/30
            eth2: 10.0.0.14/30
            eth3: 10.0.0.42/30
            eth4: 10.0.0.46/30
        spines:
            - 1.0.0.1
            - 1.0.0.2
        servers:
            - 10.2.0.2
            - 10.2.0.3
            - 10.2.0.4
            - 10.2.0.5
            - 10.2.0.6
            - 10.2.0.7
            - 10.2.0.8
            - 10.2.0.9
            - 10.2.0.10
            - 10.2.0.11
            - 10.2.0.12
            - 10.2.0.13
        server_net_ip: 10.2.0.1

    leaf3:
        ansible_docker_container: clab-tfg-frr-ansible-leaf3
        interfaces:
            lo: 2.0.0.3/32
            eth1: 10.0.0.18/30
            eth2: 10.0.0.22/30
            eth3: 10.0.0.50/30
            eth4: 10.0.0.54/30
        spines:
           - 1.0.0.1
           - 1.0.0.2
        servers:
            - 10.3.0.2
            - 10.3.0.3
            - 10.3.0.4
            - 10.3.0.5
            - 10.3.0.6
            - 10.3.0.7
            - 10.3.0.8
            - 10.3.0.9
            - 10.3.0.10
            - 10.3.0.11
            - 10.3.0.12
            - 10.3.0.13
        server_net_ip: 10.3.0.1
           
    leaf4:
        ansible_docker_container: clab-tfg-frr-ansible-leaf4
        interfaces:
            lo: 2.0.0.4/32
            eth1: 10.0.0.26/30
            eth2: 10.0.0.30/30
            eth3: 10.0.0.58/30
            eth4: 10.0.0.62/30
        spines:
            - 1.0.0.1
            - 1.0.0.2
        server_net_ip: 10.4.0.1
        servers:
            - 10.4.0.2
            - 10.4.0.3
            - 10.4.0.4
            - 10.4.0.5
            - 10.4.0.6
            - 10.4.0.7
            - 10.4.0.8
            - 10.4.0.9
            - 10.4.0.10
            - 10.4.0.11
            - 10.4.0.12
            - 10.4.0.13

    # Servers Leaf 1
    server1:
        ansible_docker_container: clab-tfg-frr-ansible-h1
        server_net_ip: 10.1.0.2
        gateway: 10.1.0.1
        leafs:
            - 10.1.0.1
        ips_vm:
            10:
                - 192.168.10.2/24
                - 192.168.10.3/24   
    server2:
        ansible_docker_container: clab-tfg-frr-ansible-h2
        server_net_ip: 10.1.0.3
        gateway: 10.1.0.1
        leafs:
            - 10.1.0.1
    server3:
        ansible_docker_container: clab-tfg-frr-ansible-h3
        server_net_ip: 10.1.0.4
        gateway: 10.1.0.1
        leafs:
            - 10.1.0.1

    server4:
        ansible_docker_container: clab-tfg-frr-ansible-h4
        server_net_ip: 10.1.0.5
        gateway: 10.1.0.1
        leafs:
            - 10.1.0.1
        
    server5:
        ansible_docker_container: clab-tfg-frr-ansible-h5
        server_net_ip: 10.1.0.6
        gateway: 10.1.0.1
        leafs:
            - 10.1.0.1
    server6:
        ansible_docker_container: clab-tfg-frr-ansible-h6
        server_net_ip: 10.1.0.7
        gateway: 10.1.0.1
        leafs:
            - 10.1.0.1
    server7:
        ansible_docker_container: clab-tfg-frr-ansible-h7
        server_net_ip: 10.1.0.8
        gateway: 10.1.0.1
        leafs:
            - 10.1.0.1
    server8:
        ansible_docker_container: clab-tfg-frr-ansible-h8
        server_net_ip: 10.1.0.9
        gateway: 10.1.0.1
        leafs:
            - 10.1.0.1
    server9:
        ansible_docker_container: clab-tfg-frr-ansible-h10
        server_net_ip: 10.1.0.10
        gateway: 10.1.0.1
        leafs:
            - 10.1.0.1
    server10:
        ansible_docker_container: clab-tfg-frr-ansible-h10
        server_net_ip: 10.1.0.11
        gateway: 10.1.0.1
        leafs:
            - 10.1.0.1
    server11:
        ansible_docker_container: clab-tfg-frr-ansible-h11
        server_net_ip: 10.1.0.12
        gateway: 10.1.0.1
        leafs:
            - 10.1.0.1
    server12:
        ansible_docker_container: clab-tfg-frr-ansible-h12
        server_net_ip: 10.1.0.13
        gateway: 10.1.0.1
        leafs:
            - 10.1.0.1

    # Servers Leaf 2
    server13:
        ansible_docker_container: clab-tfg-frr-ansible-h13
        server_net_ip: 10.2.0.2
        gateway: 10.2.0.1
        leafs:
            - 10.2.0.1
        ips_vm:
            10:
                - 192.168.10.4/24
            20:
                - 192.168.20.2/24
    server14:
        ansible_docker_container: clab-tfg-frr-ansible-h14
        server_net_ip: 10.2.0.3
        gateway: 10.2.0.1
        leafs:
            - 10.2.0.1
    server15:
        ansible_docker_container: clab-tfg-frr-ansible-h15
        server_net_ip: 10.2.0.4
        gateway: 10.2.0.1
        leafs:
            - 10.2.0.1
    server16:
        ansible_docker_container: clab-tfg-frr-ansible-h16
        server_net_ip: 10.2.0.5
        gateway: 10.2.0.1
        leafs:
            - 10.2.0.1
    server17:
        ansible_docker_container: clab-tfg-frr-ansible-h17
        server_net_ip: 10.2.0.6
        gateway: 10.2.0.1
        leafs:
            - 10.2.0.1
    server18:
        ansible_docker_container: clab-tfg-frr-ansible-h18
        server_net_ip: 10.2.0.7
        gateway: 10.2.0.1
        leafs:
            - 10.2.0.1
    server19:
        ansible_docker_container: clab-tfg-frr-ansible-h19
        server_net_ip: 10.2.0.8
        gateway: 10.2.0.1
        leafs:
            - 10.2.0.1
    server20:
        ansible_docker_container: clab-tfg-frr-ansible-h20
        server_net_ip: 10.2.0.9
        gateway: 10.2.0.1
        leafs:
            - 10.2.0.1
    server21:
        ansible_docker_container: clab-tfg-frr-ansible-h21
        server_net_ip: 10.2.0.10
        gateway: 10.2.0.1
        leafs:
            - 10.2.0.1
    server22:
        ansible_docker_container: clab-tfg-frr-ansible-h22
        server_net_ip: 10.2.0.11
        gateway: 10.2.0.1
        leafs:
            - 10.2.0.1
    server23:
        ansible_docker_container: clab-tfg-frr-ansible-h23
        server_net_ip: 10.2.0.12
        gateway: 10.2.0.1
        leafs:
            - 10.2.0.1
    server24:
        ansible_docker_container: clab-tfg-frr-ansible-h24
        server_net_ip: 10.2.0.13
        gateway: 10.2.0.1
        leafs:
            - 10.2.0.1

    # Servers Leaf 3
    server25:
        ansible_docker_container: clab-tfg-frr-ansible-h25
        server_net_ip: 10.3.0.2
        gateway: 10.3.0.1
        leafs:
            - 10.3.0.1
        ips_vm:
            10:
                - 192.168.10.5/24
            20:
                - 192.168.20.3/24
    server26:
        ansible_docker_container: clab-tfg-frr-ansible-h26
        server_net_ip: 10.3.0.3
        gateway: 10.3.0.1
        leafs:
            - 10.3.0.1
    server27:
        ansible_docker_container: clab-tfg-frr-ansible-h27
        server_net_ip: 10.3.0.4
        gateway: 10.3.0.1
        leafs:
            - 10.3.0.1
    server28:
        ansible_docker_container: clab-tfg-frr-ansible-h28
        server_net_ip: 10.3.0.5
        gateway: 10.3.0.1
        leafs:
            - 10.3.0.1
    server29:
        ansible_docker_container: clab-tfg-frr-ansible-h29
        server_net_ip: 10.3.0.6
        gateway: 10.3.0.1
        leafs:
            - 10.3.0.1
    server30:
        ansible_docker_container: clab-tfg-frr-ansible-h30
        server_net_ip: 10.3.0.7
        gateway: 10.3.0.1
        leafs:
            - 10.3.0.1
    server31:
        ansible_docker_container: clab-tfg-frr-ansible-h31
        server_net_ip: 10.3.0.8
        gateway: 10.3.0.1
        leafs:
            - 10.3.0.1
    server32:
        ansible_docker_container: clab-tfg-frr-ansible-h32
        server_net_ip: 10.3.0.9
        gateway: 10.3.0.1
        leafs:
            - 10.3.0.1
    server33:
        ansible_docker_container: clab-tfg-frr-ansible-h33
        server_net_ip: 10.3.0.10
        gateway: 10.3.0.1
        leafs:
            - 10.3.0.1
    server34:
        ansible_docker_container: clab-tfg-frr-ansible-h34
        server_net_ip: 10.3.0.11
        gateway: 10.3.0.1
        leafs:
            - 10.3.0.1
    server35:
        ansible_docker_container: clab-tfg-frr-ansible-h35
        server_net_ip: 10.3.0.12
        gateway: 10.3.0.1
        leafs:
            - 10.3.0.1
    server36:
        ansible_docker_container: clab-tfg-frr-ansible-h36
        server_net_ip: 10.3.0.13
        gateway: 10.3.0.1
        leafs:
            - 10.3.0.1
        
    # Servers Leaf 4
    server37:
        ansible_docker_container: clab-tfg-frr-ansible-h37
        server_net_ip: 10.4.0.2
        gateway: 10.4.0.1
        leafs:
            - 10.4.0.1
        ips_vm:
            30:
                - 192.168.30.4/24
    server38:
        ansible_docker_container: clab-tfg-frr-ansible-h38
        server_net_ip: 10.4.0.3
        gateway: 10.4.0.1
        leafs:
            - 10.4.0.1
    server39:
        ansible_docker_container: clab-tfg-frr-ansible-h39
        server_net_ip: 10.4.0.4
        gateway: 10.4.0.1
        leafs:
            - 10.4.0.1
    server40:
        ansible_docker_container: clab-tfg-frr-ansible-h40
        server_net_ip: 10.4.0.3
        gateway: 10.4.0.1
        leafs:
            - 10.4.0.1
    server41:
        ansible_docker_container: clab-tfg-frr-ansible-h41
        server_net_ip: 10.4.0.4
        gateway: 10.4.0.1
        leafs:
            - 10.4.0.1
    server42:
        ansible_docker_container: clab-tfg-frr-ansible-h42
        server_net_ip: 10.4.0.3
        gateway: 10.4.0.1
        leafs:
            - 10.4.0.1
    server43:
        ansible_docker_container: clab-tfg-frr-ansible-h43
        server_net_ip: 10.4.0.4
        gateway: 10.4.0.1
        leafs:
            - 10.4.0.1
    server44:
        ansible_docker_container: clab-tfg-frr-ansible-h44
        server_net_ip: 10.4.0.3
        gateway: 10.4.0.1
        leafs:
            - 10.4.0.1
    server45:
        ansible_docker_container: clab-tfg-frr-ansible-h45
        server_net_ip: 10.4.0.4
        gateway: 10.4.0.1
        leafs:
            - 10.4.0.1
    server46:
        ansible_docker_container: clab-tfg-frr-ansible-h46
        server_net_ip: 10.4.0.3
        gateway: 10.4.0.1
        leafs:
            - 10.4.0.1
    server47:
        ansible_docker_container: clab-tfg-frr-ansible-h47
        server_net_ip: 10.4.0.4
        gateway: 10.4.0.1
        leafs:
            - 10.4.0.1
    server48:
        ansible_docker_container: clab-tfg-frr-ansible-h48
        server_net_ip: 10.4.0.4
        gateway: 10.4.0.1
        leafs:
            - 10.4.0.1


spines:
    hosts:
        spine1:
        spine2:
leafs:
    hosts:
        leaf1:
        leaf2:
        leaf3:
        leaf4:

servers:
    hosts:
        server1:
        server2:
        server3:
        server4:
        server5:
        server6:
        server7:
        server8:
        server9:
        server10:
        server11:
        server12:
        server13:
        server14:
        server15:
        server16:
        server17:
        server18:
        server19:
        server20:
        server21:
        server22:
        server23:
        server24: 
        server25:
        server26:
        server27:
        server28:
        server29:
        server30:
        server31:
        server32:
        server33:
        server34:
        server35:
        server36: 
        server37:
        server38:
        server39:
        server40:
        server41:
        server42:
        server43:
        server44:
        server45:
        server46:
        server47:
        server48:  
