all:
  vars:
      ansible_user: manager
      ansible_become: true
      ansible_become_method: su
      ansible_become_user: root
      ansible_python_interpreter: /bin/ash
  hosts:
    spine1:
        ansible_host: 192.168.0.1
        interfaces:
            lo: 1.0.0.1/32
            eth1: 10.0.0.1/30
            eth2: 10.0.0.5/30
            eth3: 10.0.0.9/30
            eth4: 10.0.0.13/30
        neighbors:
            - 2.0.0.1
            - 2.0.0.2
            - 2.0.0.3
            - 2.0.0.4
    spine2:
        ansible_host: 192.168.0.2
        interfaces:
            lo: 1.0.0.2/32
            eth1: 10.0.1.1/30
            eth2: 10.0.1.5/30
            eth3: 10.0.1.9/30
            eth4: 10.0.1.13/30
        neighbors:
            - 2.0.0.1
            - 2.0.0.2
            - 2.0.0.3
            - 2.0.0.4
    leaf1:
        ansible_host: 192.168.1.1
        interfaces:
            lo: 2.0.0.1/32
            eth1: 10.0.0.2/30
            eth2: 10.0.1.2/30
        spines:
            - 1.0.0.1
            - 1.0.0.2
        servers:
            - 172.16.1.2
        server_net_ip: 172.16.1.1

    leaf2:
        ansible_host: 192.168.1.2
        interfaces:
            lo: 2.0.0.2/32
            eth1: 10.0.0.6/30
            eth2: 10.0.1.6/30
        spines:
            - 1.0.0.1
            - 1.0.0.2
        servers:
            - 172.16.2.2
        server_net_ip: 172.16.2.1
    leaf3:
        ansible_host: 192.168.1.3
        interfaces:
            lo: 2.0.0.3/32
            eth1: 10.0.0.10/30
            eth2: 10.0.1.10/30
        spines:
           - 1.0.0.1
           - 1.0.0.2
        servers:
           - 172.16.3.2
        server_net_ip: 172.16.3.1
           
    leaf4:
        ansible_host: 192.168.1.4
        interfaces:
            lo: 2.0.0.4/32
            eth1: 10.0.0.14/30
            eth2: 10.0.1.14/30
        spines:
            - 1.0.0.1
            - 1.0.0.2
        server_net_ip: 172.16.4.1
        servers:
            - 172.16.4.2
    server1:
        ansible_host: 192.168.2.1
        server_net_ip: 172.16.1.2
        gateway: 172.16.1.1
        leafs:
            - 172.16.1.1
        ips_vm:
            - 8.8.8.1/24
    server2:
        ansible_host: 192.168.2.2
        server_net_ip: 172.16.2.2
        gateway: 172.16.2.1
        leafs:
            - 172.16.2.1
        ips_vm:
            - 8.8.8.2/24
    server3:
        ansible_host: 192.168.2.3
        server_net_ip: 172.16.3.2
        gateway: 172.16.3.1
        leafs:
            - 172.16.3.1
    server4:
        ansible_host: 192.168.2.4
        server_net_ip: 172.16.4.2
        gateway: 172.16.4.1
        leafs:
           - 172.16.4.1
  
spines:
    hosts:
        spine1:
        spine2:
leafs:
    hosts:
        leaf1:
        leaf2:
        leaf3:
        leaf4:

servers:
    hosts:
        server1:
        server2:
        server3:
        server4:
      
      
