- name: Configurar los leafs
  hosts: leafs
  gather_facts: no
  become: yes
  become_method: su
  become_user: root

 
 

  tasks:
    - name: Cargar la configuraci칩n de las interfaces del nodo
      raw: |
        vtysh -c "configure terminal" \
        vtysh -c "interface {{ item.key }}" \
        vtysh -c "ip address {{ item.value }}" \
        vtysh -c "ip ospf area 0" \ 
        vtysh -c "exit" 
    
      loop: "{{ interfaces | dict2items }}"
      
      when: interfaces is defined
    - name: Activar OSPF
      raw: |
        vtysh -c "configure terminal" \
        vtysh -c "router ospf" \
        vtysh -c "exit" 
        
    - name: Configurar spines
      raw: |
        vtysh -c "configure terminal" \
        vtysh -c "router bgp 65100" \
        vtysh -c "neighbor spines peer-group" \
        vtysh -c "neighbor spines remote-as 65100" \
        vtysh -c "neighbor spines update-source lo" \
        vtysh -c "exit" \
        vtysh -c "exit" 
    - name: Configurar vecinos spines
      raw: |
        vtysh -c "configure terminal" \
        vtysh -c "router bgp 65100" \
        vtysh -c "neighbor {{ item }} peer-group spines" \
        vtysh -c "exit" \
        vtysh -c "exit"
      with_items: "{{ spines }}"
      when: spines is defined
      
    - name: Configurar servidores
      raw: |
        vtysh -c "configure terminal" \
        vtysh -c "router bgp 65100" \
        vtysh -c "neighbor servers peer-group" \
        vtysh -c "neighbor servers remote-as 65100" \
        vtysh -c "neighbor servers update-source lo" \
        vtysh -c "address-family l2vpn evpn" \
        vtysh -c "neighbor servers route-reflector-client" \
        vtysh -c "neighbor servers activate" \
        vtysh -c "advertise-all-vni" \
        vtysh -c "exit" \
        vtysh -c "exit" \
        vtysh -c "exit" 
    - name: Configurar vecinos servidores 
      raw: |
        vtysh -c "configure terminal" \
        vtysh -c "router bgp 65100" \
        vtysh -c "neighbor {{ item }} peer-group servers" \
        vtysh -c "exit" \
        vtysh -c "exit"
      with_items: "{{ servers }}"
      when: servers is defined  
    

    - name: Crear el bridge
      raw: |
        ip link add br0 type bridge 
        ip link set br0 up 
        
    - name: A침adir puertos al brige
      raw: |
        ip link set {{ item }} master br0 
        ip link set {{ item }} up 
      with_items: [eth3, eth4, eth5, eth6, eth7, eth8, eth9, eth10, eth11, eth12]

    - name: Direcci칩n en red de servidors 
      raw: |
        vtysh -c "configure terminal" \
        vtysh -c "interface br0" \
        vtysh -c "ip address {{ server_net_ip }}/24" \
        vtysh -c "ip ospf area 0" \
        vtysh -c "exit" \
        vtysh -c "exit"
      when: server_net_ip is defined 
#         
    - name: "Guardar la configuraci칩n"
      raw: |
        vtysh -c "copy running-config startup-config"
    
    
