 # playbooks/overlay_conf.yaml
 - name: Levantar VMs simuladas en VXLAN
   hosts: servers
   gather_facts: no
   connection: local

   vars:
     ansible_python_interpreter: /usr/bin/python3

   tasks:
    - name: Crear el bridge
      raw: |
          ip link add br0 type bridge
          ip link set br0 up

    - name: Crea una simulación de máquina virtual
      raw: |
          ip link add vxlan100 type vxlan id 100 local {{ server_net_ip }}
          ip link set vxlan100 up
          ip link set vxlan100 master br0
          ip link add veth1 type veth peer name veth_vm
          ip link set veth1 master br0
          ip link set veth1 up
          ip netns add vm1
          ip link set veth_vm up
          ip link set veth_vm netns vm1
          ip netns exec vm1 ip addr add {{ item }} dev veth_vm
          ip netns exec vm1 ip link set veth_vm up
      with_items: "{{ ips_vm }}"
      when: ips_vm is defined
