- name: Configurar las VMs
  hosts: servers
  gather_facts: no
  connection: local
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Crea una simulación de máquina virtual
      shell: |
        
        docker exec {{ansible_docker_container}} ip link add br0 type bridge
        docker exec {{ansible_docker_container}} ip link set br0 up        
        
        docker exec {{ansible_docker_container}} ip link add vxlan{{vxlan_id}} type vxlan id {{vxlan_id}} dev eth1 local {{ server_net_ip }}
        docker exec {{ansible_docker_container}} ip link set vxlan{{vxlan_id}} master br0
        docker exec {{ansible_docker_container}} ip link set vxlan{{vxlan_id}} up
        
        docker exec {{ansible_docker_container}} ip netns add {{ns_name}}
        docker exec {{ansible_docker_container}} ip link add {{veth[0]}} type veth peer name {{veth[1]}}
        docker exec {{ansible_docker_container}} ip link set {{veth[0]}} master br0
        docker exec {{ansible_docker_container}} ip link set {{veth[0]}} up
        docker exec {{ansible_docker_container}} ip link set {{veth[1]}} netns {{ns_name}}
        docker exec {{ansible_docker_container}} ip netns exec {{ns_name}} ip link set lo up
        docker exec {{ansible_docker_container}} ip netns exec {{ns_name}} ip link set {{veth[1]}} up
        docker exec {{ansible_docker_container}} ip netns exec {{ns_name}} ip address add {{ns_ip}} dev {{veth[1]}}

    - name: "Guardar la configuración"
      shell: |
        docker exec {{ ansible_docker_container }} vtysh -c "copy running-config startup-config"
